name: flutter_fb_insta_clone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  get: 4.6.1
  flutter: 
    sdk: flutter
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.7
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+7
  intl: ^0.17.0
  uuid: ^3.0.5
  device_preview: ^1.0.0
  infinite_scroll_pagination: ^3.1.0
  dio: ^4.0.4
  email_validator: ^2.0.1
  flutter_form_builder: ^7.1.0
  form_builder_validators: ^7.4.0
  flutter_spinkit: ^5.1.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/svg/

