// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARrVz83D8OpOsY2_PN2LzIn5RPU1i8fxI',
    appId: '1:123146519137:web:fe1cbfe1aabf2f1e1f2020',
    messagingSenderId: '123146519137',
    projectId: 'flutter-insta-clone-ab7ff',
    authDomain: 'flutter-insta-clone-ab7ff.firebaseapp.com',
    storageBucket: 'flutter-insta-clone-ab7ff.appspot.com',
    measurementId: 'G-JVEQXQQSHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtymxIwB7Ko7vkcaDTZUkuuj_lqDIF_WU',
    appId: '1:123146519137:android:3ae571bd7df943871f2020',
    messagingSenderId: '123146519137',
    projectId: 'flutter-insta-clone-ab7ff',
    storageBucket: 'flutter-insta-clone-ab7ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM7DhYDsJT-mw00sS9P9IAOzhX0RsQYkU',
    appId: '1:123146519137:ios:08085e940a874b8e1f2020',
    messagingSenderId: '123146519137',
    projectId: 'flutter-insta-clone-ab7ff',
    storageBucket: 'flutter-insta-clone-ab7ff.appspot.com',
    iosClientId: '123146519137-60iqg80g42c16aefdegimmhl3isb2orc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFbInstaClone',
  );
}
